In [2]:
import numpy as np

array1 = np.arange(5)
array2 = [5,6,7,8,9]

array3 = array1 + array2
array3

array([ 5,  7,  9, 11, 13])

In [3]:
array4 = array3 * 2
array4

array([10, 14, 18, 22, 26])

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A+B
print(C)

[[ 6  8]
 [10 12]]


In [9]:
D = A*B
print(D)

[[ 5 12]
 [21 32]]


In [7]:
G = D*2
print(G)

[[10 24]
 [42 64]]


In [8]:
M = A@B
print(M)

[[19 22]
 [43 50]]


In [ ]:
N = np.random.random((2,2))
print(N)

[[0.44261604 0.73241157]
 [0.83230501 0.01634832]]


In [ ]:
testArray = np.arange(9)
K = np.reshape(testArray, (3,3))
K

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])